name: Flushing realtime logs

on:
  schedule:
    # Cron syntax: "min hour day month day_of_week"
    - cron: '30 18 * * *'  # At 18:30 UTC everyday (12:00 AM IST)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Flush logs
        run: |
          python Server/Logs/flushRealtimeLogs.py
      - name: Check if log is already flushed
        id: check_changes
        run: |
          if git diff --quiet HEAD -- Server/Data_Files/last_run.json; then
            echo "No changes detected in last_run.json"
            echo "changes_detected=false" >> $GITHUB_ENV
          else
            echo "Changes detected in last_run.json"
            echo "changes_detected=true" >> $GITHUB_ENV
          fi
      - name: Configure Git
        run: |
          git config --global user.name "sik-sak"
          git config --global user.email "siksak2024@gmail.com"
          git pull
          
      - name: Commit logs
        if: env.changes_detected == 'true'
        run: |
            git add Server/Logs/realtimeFetchLogs.log
            git commit -m "Flushed logs on $(date '+%Y-%m-%d %H:%M:%S')"
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push